### ISSUE TITLE
package is not available

### ISSUE THREAD

**Issue by WalterShe** [jamescauwelier/PSRedis#15]
"require": {
         "jamescauwelier/psredis": "*"
	},
then 
![qq 20150805171514](https://cloud.githubusercontent.com/assets/491880/9082282/893f9d78-3b95-11e5-89f1-1948efb8fe28.png)

**Comment by jamescauwelier** [comment]
@WalterShe use the following instead:

```
"require": {
        "jamescauwelier/psredis": "~1.0"
    },
```

Did you have a minimal stability flag set?  I have made a stable release now, but that was most probably the issue.  I also moved the package to a new location so that could have created this issue as well.

Let me know if this works for you?
