### ISSUE TITLE
how do i use psredis?

### ISSUE THREAD

**Issue by thestick613** [jamescauwelier/PSRedis#19]
i'm kind of new to php. I've run
```
wget https://getcomposer.org/installer
php installer
php composer.phar install
```

I've put this file in the same folder:` my_sentinel.php`
```
<?php
require '../vendor/autoload.php';

$sentinel1 = new Client('127.0.0.1', '26379');
?>
```
but when i run php my_sentinel.php, i get
`PHP Fatal error:  Class 'Client' not found in /path/to/my_sentinel.php on line 4`

**Comment by jamescauwelier** [comment]
@thestick613 Do you have a link to your PHP project on github?

The first thing that I would do is to install composer globally by also doing this after your first code block (I am assuming you are using some kind of unix OS):

```
$ mv composer.phar /usr/local/bin/composer
```

The other suggestion I have is to declare a namespace in your PHP file and load the correct namespace from the sentinel library.  A proper IDE will assist you in auto-completing this code for you.  I use PHPStorm.

Let me know if that solves your problem?

**Comment by thestick613** [comment]
I just need the minimal example to make a connection to my sentinel cluster. I don't actually know any php, i'm just trying to help someone else. I will probably not install phpstorm only for this :)

**Comment by jamescauwelier** [comment]
@thestick613 Use the fully qualified name, like this `new \ PSRedis\Client(...)`  More information on namespaces can be found [here](http://php.net/manual/en/language.namespaces.basics.php).

Also, maybe the other person should be dropping by here and asking questions if they need a working PHP example?
