### ISSUE TITLE
How to set the sentinels'  password and name

### ISSUE THREAD

**Issue by zsz91** [jamescauwelier/PSRedis#29]

**Comment by zsz91** [comment]
Thanks for open the codes   but  I find your code in  ConnectingTest.php  not have the place to set sentinel's password and name? 
by the way  I am a Chinese PHP Coder
-------------------------------------------------------------------------------------------------------------

**Comment by jamescauwelier** [comment]
Hi @zsz91 

Please have a look at the following issue dealing with the same question.  Browse to the end and let me know if that solves your issue?  I might have to add some documentation for this as you're the second asking recently.

**Comment by zsz91** [comment]
I had solved the problem by use predis/examples/replication_sentinel.php .  Thank your reply.
